### PR TITLE
TMDM-9707 Remain page size setting of foreign key window.

### PR DESCRIPTION
**Pull request by yjli-talend**

### CODE REVIEW

**Comment by qcui** [comment]
This change will make ForeignKeyListWindow for each FK sharing the same pageSize setting.

**Comment by qcui** [comment]
Validated.

**Comment by pbabin** [comment]
isPagingAccurate method was introduced when using Qizx. It shouldn't be there any more.

**Comment by yjli-talend** [comment]
Method PagingToolBarEx(int pageSize) still be called in browserecords project,so it can't be made of private.

**Pull request merged**
